### ISSUE TITLE
Add a default start date

### ISSUE THREAD

**Issue by drewhoffer** [uselessdev/datepicker#14]
It would be nice if a default start date was given if I choose not to give one.

**Comment by uselessdev** [comment]
Hi @drewhoffer 

I don't believe that a default date is really necessary.

The idea here is that the calendar works as an html input, if you don't add an initial value for it, the input doesn't have any value until it's changed.

With this in mind, let's talk about the Calendar, to deicides how to render the component if an initial value is not provided this uses the current date (`new Date()`). If you really need to show a pre-selected date (or a default date) you can use the `value` prop.
