### ISSUE TITLE
Show current date

### ISSUE THREAD

**Issue by stanislavnastasiu-dev** [uselessdev/datepicker#19]
It would be nice to be able to see the current day. 
Something like this:
![asd](https://user-images.githubusercontent.com/77984129/158676595-3e7a17b3-3927-45cc-9a8f-0b13dc6ef927.png)

**Comment by uselessdev** [comment]
Hi @stanislavnastasiu-dev thanks for opening this issue, this is something that I already have planned to do, I think it'll be released in a couple of days.

**Comment by uselessdev** [comment]
hi @stanislavnastasiu-dev this was added in #24 and publish with the [v2.2.1](https://github.com/uselessdev/datepicker/releases/tag/v2.2.1)

**Comment by stanislavnastasiu-dev** [comment]
Hi sorry to re-open this thread but i there seems to be some problem with the types of the last update [v2.2.1](https://github.com/uselessdev/datepicker/releases/tag/v2.2.1). 
My package.json reports the correct version "@uselessdev/datepicker": "^2.2.1",
I updated the package and tried to use the new property but i get an error that it doesn't exist. If i look in the src folder in Calendart.tsx the changes reported in the commit are there but if i open ./dist/index.d.ts it doesn't reflect the new property. I tried re-installing, deleteing the node_modules folder and re-install all but without success.

**Comment by uselessdev** [comment]
@stanislavnastasiu-dev thanks for reporting, I take a look soon.

**Comment by uselessdev** [comment]
hi @stanislavnastasiu-dev I have published the [v2.2.2](https://github.com/uselessdev/datepicker/releases/tag/v2.2.2) this should fix the problem with the missing prop in types.

sorry for the delay.

**Comment by stanislavnastasiu-dev** [comment]
thanks! it works as expected now
