### ISSUE TITLE
Disable dates after/before certain date

### ISSUE THREAD

**Issue by branislaav** [uselessdev/datepicker#28]
It would be useful if props `disablePastDates`, `disableFutureDates` could take a date as an option. Alternatively, it could be new props called `disablePastDatesFrom`, `disableFutureDatesFrom`.
In my case, I need to allow users to select only a certain range let's say from January first to February second. I need all other dates to be disabled.
I can make PR for that if it is okay.

**Comment by uselessdev** [comment]
Hi @branislaav thanks for reporting, I appreciate it if you can make a pull request.

**Comment by uselessdev** [comment]
@branislaav this was released in [v2.3.0](https://github.com/uselessdev/datepicker/releases/tag/v2.3.0) thanks again
