### ISSUE TITLE
Date format dd/MM/yyyy with input and singleDateSelection

### ISSUE THREAD

**Issue by wilsonfaustino** [uselessdev/datepicker#37]
Hi!
I'm trying to use it in a NextJS project and I'm facing some issues.
When I try to implement with format dd/MM/yyyy with input as the example given I face an error as followed.
![image](https://user-images.githubusercontent.com/25889686/168333934-937d3966-9b55-4a87-9df5-155ea8202415.png)

Any hints on how to fix it?

Thanks in advance.

**Comment by uselessdev** [comment]
Hi @wilsonfaustino, thanks for reporting this.

To be honest, I don't know what is the problem, do you have a repository or something where I can take a look?

Also, I'll try to reproduce this if a nextjs application.

**Comment by wilsonfaustino** [comment]
Thank you for the fast response.

here you can find a repo with this issue.
[https://github.com/wilsonfaustino/testDatePicker](https://github.com/wilsonfaustino/testDatePicker)

The first time you pick the date it works fine, but when you try to edit it again the app crashes.

**Comment by wilsonfaustino** [comment]
Hi, @uselessdev ! 
I was making a mistake with Date object. 

Solved by passing the right values like bellow
```JS
useEffect(() => {
        if (match(value)) {
            const [ day, month, year ] = value.split('/')
            const date = new Date(+year, +month - 1, +day)

            return setDate(date)
        }
    }, [value])
```

**Comment by uselessdev** [comment]
Oh, nice! So I'll close this issue for now, if you have any trouble with datepicker let me know. 😊
