### ISSUE TITLE
Custom theme styles not applied to custom control buttons

### ISSUE THREAD

**Issue by Philzen** [uselessdev/datepicker#51]
Using https://uselessdev-datepicker.netlify.app/?path=/docs/calendar--custom-control-buttons, the theme customizations made in a seperate `datepicker.ts` theme file (as outlined in the README and working fine for non-custom control buttons) are not applied to the custom button.

**Comment by Philzen** [comment]
I believe simply changing 
- https://github.com/uselessdev/datepicker/blob/main/src/control-next-button.tsx#L18 and
- https://github.com/uselessdev/datepicker/blob/main/src/control-prev-button.tsx#L18

to:

```ts
  if (as) {
    return as({ onClick: nextMonth, sx: styles.button })
  }
```

will fix.

**Comment by uselessdev** [comment]
Thanks for opening this issue @Philzen I'll take a look.

**Comment by Philzen** [comment]
Current workaround is to basically repeat what is being done in the datepicker implementation and apply the styles to the custom `as`-button:

```ts
  const { button: buttonStyles } = useMultiStyleConfig('CalendarControl', {})

// .... further down :

            <CalendarPrevButton
              as={(props) => (
                <IconButton
                  aria-label={t('calendar.controlPrev')}
                  sx={buttonStyles}
                  {...props}
                  icon={<IoArrowUpSharp />}
                />
              )}
            />
```

**Comment by Philzen** [comment]
See https://github.com/uselessdev/datepicker/pull/58#issuecomment-1166386173 – applying the fix as suggested in the initial issue description would mean a breaking change for anyone currently using this custom-rolled `as`-prop.

As suggested there, i'd do the breaking change at some point in the future to harmonize behaviour with [Chakra UI `as`-prop](https://chakra-ui.com/community/recipes/as-prop). In the meanwhile i guess the workaround above is sufficient enough.

**Comment by uselessdev** [comment]
Hi @Philzen sorry for the late reply here, I was looking for a way to solve this but the problem with this approach:

```
return as({ onClick: nextMonth, sx: styles.button })
```

Is that `sx` prop have prior over the other styles props, so if we do this, all syles that are added in the `as` prop are ignored/overwritten by the `sx` (the theme styles)

**Comment by Philzen** [comment]
>so if we do this, all syles that are added in the `as` prop are ignored/overwritten by the `sx` (the theme styles)

That's why i've redrawn my PR. It's actually the behaviour i was after (i'm styling everything through custom theme files and just needed to change the icon), but after firing up storybook locally and comparing the change with the current style, i realized it would be a severe breaking change.
