### ISSUE TITLE
Today Date style overrides selected style (=selection not visible)

### ISSUE THREAD

**Issue by Philzen** [uselessdev/datepicker#52]
Can be seen at https://uselessdev-datepicker.netlify.app/?path=/docs/calendar--highlight-today

Although one can select today's date, the style doesn't change as it does on every other day.

It seems that variant `CalendarDay.variants.today` has a higher priority than `CalendarDay.variants.selected` and thus overrides selected styles, while it should be vice versa.

**Comment by uselessdev** [comment]
Thanks again @Philzen

**Comment by Philzen** [comment]
Thanks to you @uselessdev – also for creating this awesome component! :heart: 

This fixes the apparent issue at hand, but i realize there is a use case that i'm after that currently doesn't seems possible. This what our datepicker looks like now:

![grafik](https://user-images.githubusercontent.com/1634615/175792123-edfda369-919a-4abf-aa80-05d96e000619.png)

28th of June is selected, today is the 26th. What i would love to achieve is a variant that does not exist yet: today + selected, so that in our case, the current day would simply get a border but still be recognizable as the current day. I can see two ways to achieve this:

1. have `selected` variant be added instead to the current style instead of replacing them.  
   May be easily possible using the spread operator, but possibly pose a breaking change for people using v2.5.0 and relying on the current behaviour
2. introduce a new `CalendarDay.variants.todaySelected` that could be styled separately

I'd love to hear what you think. Of course, this may be off-topic for this bug-related issue, so i could very well create a new one for this feature / enhancement.
