### ISSUE TITLE
Question: Why would `isValid`-check be needed `onSelectDate`

### ISSUE THREAD

**Issue by Philzen** [uselessdev/datepicker#61]
Just a theoretical question: Is there any scenario in which the date supplied to the `handleSelectDate`-callback would not be valid?

https://github.com/uselessdev/datepicker/blob/adeed73e58dd6f96b3a7d0c04cef729b4a8a8bfa/src/calendar.stories.tsx#L387

Our implementation is based on this example and i couldn't reproduce or think of a scenario where the supplied date becomes invalid, that's why i wanted to ask.

**Comment by Philzen** [comment]
> the user can pass an invalid date

How could the user pass an invalid date into handleSelectDate – as far as i can see that is the exclusive handler for the component. Or is there a case in which the component could pass an invalid date?

**Comment by uselessdev** [comment]
The library doesn't validate the input value, it only renders the calendar, so, if you don't validate the user can do something like this:

https://user-images.githubusercontent.com/6943919/177431683-2ac5fa64-741d-45e5-9a15-08611e2494b9.mov

**note that input is not part of the calendar, it's an example of implementation/usage**

And as you can see the invalid value is updated in the state and passed to the Calendar, and it throws an error.

**Comment by Philzen** [comment]
I am very thankful for your reply, but i believe we still have a misunderstanding. I am *exclusively* referring to `handleSelectDate`. 

Any manual input through the `<input>`-field is processed through `handleInputChange` and absolutely requires proper validation as it cannot be trusted to be parseable – i have actually already built slightly more complex, fully l10n-customizable version of that (on top of your excellent example and `date-fns/locale`)  for our project, so i'm completely aware of that.

Sorry for the kerfuffle. But my only question is and was – why would i need any validation such as `isValid` in `handleSelectDate`?

**Comment by uselessdev** [comment]
> why would i need any validation such as isValid in handleSelectDate?

You don't need, maybe when you are working with `start, end` dates

**Comment by Philzen** [comment]
Cheers – that's all a wanted to know :)

Just wanted to make sure there is no fringe state that could happen and make my code fail, as i removed that in my implementation.
