### ISSUE TITLE
should be possible to have more than one variant ('today', 'range',  'selected') at the same time

### ISSUE THREAD

**Issue by nlfonseca** [uselessdev/datepicker#62]
First of all, great datepicker built with chakra 👏 

on the useCalendarDay in my opinion `variant` should be an array since is possible to have two variants at the same time 
['today', 'selected'] or ['today', 'range']

example of MUI with `variant`, 'today' and 'range'.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/7745591/178319125-264e610b-5a01-4eda-9a7e-f73b9a186964.png">

**Comment by uselessdev** [comment]
Hi, @nlfonseca thanks for opening this issue.

By the way chakra-ui handle with `variants` we can't have two variants at the same time for one component, so, to be able to do something like this we can't use `variants`

A possible approach to do this would be using a custom component for `day`, you can see an example of use here: https://github.com/uselessdev/datepicker/blob/main/src/calendar.stories.tsx#L763-L828
