### ISSUE TITLE
Skipping years

### ISSUE THREAD

**Issue by kennym** [uselessdev/datepicker#63]
First of all, great and well-written package!

I wonder if it's possible to skip years, not only months. It's a requirement I have for my app, and wonder if this needs to be added or could be easily customized?

**Comment by uselessdev** [comment]
Hi, @kennym thanks,

> I wonder if it's possible to skip years, not only months. It's a requirement I have for my app, and wonder if this needs to be added or could be easily customized?

Yes, I'm working on the next release that allows us to easily do this, but at this moment there's no way to customize this sadly.

**Comment by kennym** [comment]
@uselessdev I implemented something very quickly with #64 ... this will do for now for my project. Let me know if this is totally different from what you had in mind for an implementation.

**Comment by uselessdev** [comment]
Hi @kennym sorry for the late reply, I publish an alpha [release](https://www.npmjs.com/package/@uselessdev/datepicker/v/3.0.0-alpha) for `v3.0.0` it's possible to test if it works for you?

**Comment by kennym** [comment]
@uselessdev I've done the very same thing in my PR :-)

**Comment by joycenn** [comment]
> Hi @kennym sorry for the late reply, I publish an alpha [release](https://www.npmjs.com/package/@uselessdev/datepicker/v/3.0.0-alpha) for `v3.0.0` it's possible to test if it works for you?
> 
> You can see an example of how this should work here:
> 
> https://github.com/uselessdev/datepicker/blob/next/stories/calendar.stories.tsx#L24-L45
> 
> and as you can see [here](https://github.com/uselessdev/datepicker/blob/next/src/hooks/use-calendar.tsx#L63-L71) the `useCalendar` export `onNextYear` and `onPrevYear` so by this you can add a custom button to handle with this.

How to fix this error ?
![image](https://user-images.githubusercontent.com/110002107/182760438-01d8ebeb-1723-45fa-bece-30d1c6ec4c65.png)

**Comment by uselessdev** [comment]
I'm not sure @joycenn

**Comment by joycenn** [comment]
Is it working on your end ?

**Comment by uselessdev** [comment]
Yes, but I'll investigate it to make sure

**Comment by uselessdev** [comment]
Hi @joycenn I've made some tests and there's a bug, but I think it's solved in the `v3.0.0-rc.2` unfortunately there is another bug in the theme, and I'm working on this one.
