### ISSUE TITLE
Duplicate key issue in US locale

### ISSUE THREAD

**Issue by CuriouslyCory** [uselessdev/datepicker#70]
There's a key issue where it's using the weekday names. In the US locale there are 2 S's and 2 T's causing duplicate key issues. 
Created PR to resolve: https://github.com/uselessdev/datepicker/pull/69

**Comment by uselessdev** [comment]
solved in [v2.7.0](https://github.com/uselessdev/datepicker/releases/tag/v2.7.0)

(sorry for the delay 😪 )
