### ISSUE TITLE
How can we custom the date format e.g. dd/MM/yyyy

### ISSUE THREAD

**Issue by ImBIOS** [uselessdev/datepicker#77]
## Problem

I need to create Date Range Picker with `dd/MM/yyyy` format, but It's hard to find docs about it.

## Suggested Solution

Create a full docs of usage coverage, start with how to custom the format of the input date.

**Comment by uselessdev** [comment]
You can do this on your component that uses the calendar, you can see an example in this story https://github.com/uselessdev/datepicker/blob/main/src/calendar.stories.tsx#L387
