### ISSUE TITLE
How do I customise the style of the day highlighted by `highlightToday`?

### ISSUE THREAD

**Issue by hjball** [uselessdev/datepicker#78]
<img width="563" alt="Screenshot 2023-04-28 at 07 08 14" src="https://user-images.githubusercontent.com/30578846/235067877-89d7813c-27de-4779-a1ef-22203cbd3407.png">

The only identifiable selector is `aria-label=[today]` which isn't ideal and I can't find a better solution in the docs.

**Comment by uselessdev** [comment]
Hi @hjball ideally you would use the theme config from chakra-ui [like here](https://github.com/uselessdev/datepicker/blob/main/src/theme/day.ts#L55-L60) if not possible, you can use a [custom component](https://github.com/uselessdev/datepicker/blob/main/src/theme/day.ts#L55-L60)
